---
apiVersion: v1
kind: Pod
metadata:
  name: foo-2
spec:
  containers:
    - name: foo
      image: 966775768564.dkr.ecr.us-east-1.amazonaws.com/foo:latest
      ports:
        - containerPort: 8080
      securityContext:
        readOnlyRootFilesystem: true
