---
apiVersion: v1
kind: Service
metadata:
  name: {{ required "requires Values.app to be set" .Values.app }}
spec:
  selector:
    # This is the label to route all traffic to
    app: {{ required "requires Values.app to be set" .Values.app }}
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
