---
apiVersion: v1
kind: Service
metadata:
  name: foo
spec:
  selector:
    # This is the label to route all traffic to
    app: foo
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
